### ISSUE TITLE
Apple pay has stopped working on Desktop version. Still Working in mobile

### ISSUE THREAD

**Issue by DannyRussellWP** [GoogleChromeLabs/appr-wrapper#1]
Hi,
   I noticed on monday that Apple pay on Desktop safari (Version 10.1.1 (12603.2.4)) stopped working on my dummy site which uses your wrapper. It has continued to work on mobile safari. I have tested your dummy site and you are having the same issue. 

Having debugged both your site and mine the behaviour is the same:

- CanMakePayment responds with true
- Then paymentrequest.show() never seems to respond.
- Occasionally the catch section is invoked but the error is undefined.

I have tested on multiple laptops. Please let me know if you need anymore information

**Comment by agektmr** [comment]
Hi @DannyRussellWP thanks for the report!
Do you know if other websites (without appr-wrapper) working fine with Apple Pay JS on desktop?

**Comment by jackbrycesmith** [comment]
Had the same issue using the iOS simulator on Mac (iPhone X, iOS11)

- Worked fine: https://stripe.com/docs/apple-pay/web
- Didn't work: https://web-payment-apis.appspot.com/

**Comment by DannyRussellWP** [comment]
After i successfully tested it on my wife's laptop I rebooted my laptop and it worked fine. Sorry for the false alarm!

**Comment by agektmr** [comment]
Thanks @DannyRussellWP for the confirmation.
@codesplain How is yours?

**Comment by jackbrycesmith** [comment]
@agektmr False alarm as well apologies! Noticed I was connecting to the HTTP version of web-payment-apis.appspot.com

**Comment by agektmr** [comment]
@codesplain Thanks for letting me know. I actually made similar mistake. I should probably set HSTS for demo server. Will raise a new issue.
