### ISSUE TITLE
demo broken until rebuild with #3

### ISSUE THREAD

**Issue by autonome** [GoogleChromeLabs/appr-wrapper#4]
The demo at https://web-payment-apis.appspot.com/ is broken until updated with the fix in #3.

**Comment by agektmr** [comment]
@autonome Will update the demo site later. Thanks for the notice.

**Comment by agektmr** [comment]
This issue should have been fixed by now.
I've checked with Firefox Nightly.

**Comment by autonome** [comment]
Working now, thanks :D

**Comment by atiris** [comment]
It is here again.  
_404. That’s an error._  
_The requested URL was not found on this server. That’s all we know._

**Comment by agektmr** [comment]
@atiris It's turned down intentionally for some reason. Do you need the demo server running?

**Comment by atiris** [comment]
Ok, I just wanted to see how it works... and it didn't work :smile: .. so I reported it for sure :wink:
