### ISSUE TITLE
Payment Request in Safari

### ISSUE THREAD

**Issue by interpegasus** [GoogleChromeLabs/appr-wrapper#8]
Hi, Thank you for sharing the demo.

In a test, the official demo does not display the payment request button in Safari

I would like to know if it is compatible with Safari on macOS and iOS? Or if it only works in Chrome?

Thank you!

Regards

**Comment by agektmr** [comment]
@interpegasus Sorry for lagged response. It has been broken for sometime but I have fixed the demo site a while back. Can you try it once again now? It's supposed to work on both Safari and Chrome.
With my latest change, on Safari it uses native Payment Request API if available, appr-wrapper if only Apple Pay JS is available.

**Comment by PunkHaz4rd** [comment]
It's not working on either appr-wrapper implementation (button not showing) nor on Native implementation (The operation was aborted).

**Comment by agektmr** [comment]
@PunkHaz4rd That's probably because you haven't stored a credit card information in the browser / Apple Pay yet. Let me make it clear when there are no credit card information available.
